"""Core BLE connection, device discovery, and profile definitions."""

from nuanic_ring.core.connector import NuanicConnector
from nuanic_ring.core.profiles import (
    BATTERY_UUID,
    COMMAND_UUID,
    IMU_BATCH_UUID,
    LIVE_DNE_UUID,
    LIVE_EDA_UUID,
    MOODMETRIC_PROFILE,
    MOODMETRIC_SERVICE_UUIDS,
    NOTIFY_UUIDS_BY_PROFILE,
    NUANIC_PROFILE,
    NUANIC_SERVICE_UUID,
    REALTIME_UUID,
    SAMPLE_RATE_UUID,
    STATE_UUID,
    STORAGE_FORMAT_UUID,
    STORAGE_REWIND_UUID,
    STORAGE_USAGE_UUID,
    STORAGE_UUID,
    UNKNOWN_PROFILE,
    detect_ring_profile_from_service_uuids,
    notify_uuids_for_profile,
)
from nuanic_ring.core.scanner import (
    RingScanner,
    _get_windows_paired_rings,
    _load_last_address,
    _reset_bluetooth_radio,
    _sanitize_address,
    _sanitize_name,
    _save_last_address,
)

__all__ = [
    "NuanicConnector",
    "RingScanner",
    "NUANIC_PROFILE",
    "MOODMETRIC_PROFILE",
    "UNKNOWN_PROFILE",
    "NUANIC_SERVICE_UUID",
    "MOODMETRIC_SERVICE_UUIDS",
    "NOTIFY_UUIDS_BY_PROFILE",
    "STATE_UUID",
    "SAMPLE_RATE_UUID",
    "REALTIME_UUID",
    "LIVE_DNE_UUID",
    "LIVE_EDA_UUID",
    "STORAGE_UUID",
    "STORAGE_FORMAT_UUID",
    "STORAGE_REWIND_UUID",
    "STORAGE_USAGE_UUID",
    "COMMAND_UUID",
    "IMU_BATCH_UUID",
    "BATTERY_UUID",
    "detect_ring_profile_from_service_uuids",
    "notify_uuids_for_profile",
    "_sanitize_address",
    "_sanitize_name",
    "_save_last_address",
    "_load_last_address",
    "_reset_bluetooth_radio",
    "_get_windows_paired_rings",
]
